
security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'

github:
  client:
    clientId: Iv1.acbf7009a5610786
    clientSecret: 90186ec1737e015cfe7ad3ca4fb58a69a5b272ba
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

local:
  client:
    clientId: client_id
    clientSecret: client_secret
    accessTokenUri: http://127.0.0.1:8000/login/oauth2/token/
    userAuthorizationUri: http://127.0.0.1:8000/login/oauth2/authorize
    clientAuthenticationScheme: form
    scope:
          - profile
          - bookmarks
  resource:
    userInfoUri: http://127.0.0.1:8000/api/v1/accounts/me/

---
spring:
    profiles: dev
    jpa:
        database-platform: org.hibernate.dialect.DerbyDialect
        generate-ddl: false
        show-sql: false
        hibernate:
            ddl-auto: create-drop
            properties:
               hibernate:
                  dialect: org.hibernate.dialect.DerbyDialect
        properties:
            hibernate:
            format_sql: true 

server:
    address: 127.0.0.1

---
spring:
    profiles: prod
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      generate-ddl: false
      show-sql: false
      hibernate:
          ddl-auto: none
          properties:
              hibernate:
                  dialect: org.hibernate.dialect.PostgreSQLDialect
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://192.168.1.100:5432/mywebmarks2
        username: mynotes
        password: mynotes
     

server:
    address: 127.0.0.1
    port: 8080

logging:
      file: logs/application-debug.log
      level:
        root: WARN        
        org.springframework.web: ERROR
        org.springframework.security: ERROR
        org.hibernate: ERROR
        com.emu.apps: WARN
