
security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'

github:
  client:
    clientId: Iv1.acbf7009a5610786
    clientSecret: 90186ec1737e015cfe7ad3ca4fb58a69a5b272ba
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

webmarks:
  client:
    clientId: client_id
    clientSecret: client_secret
    accessTokenUri: http://oauth2.webmarks.net/login/oauth2/token/
    userAuthorizationUri: http://oauth2.webmarks.net/login/oauth2/authorize
    clientAuthenticationScheme: form
    scope:
          - profile
          - bookmarks
  resource:
    userInfoUri: http://oauth2.webmarks.net/api/v1/accounts/me/

logging:
      # file: logs/application-debug.logger
      level:
        root: WARN
        org.springframework.web: ERROR
        org.springframework.security: ERROR
        org.hibernate: ERROR
        org.hibernate.SQL: DEBUG
        org.hibernate.type.descriptor.sql: WARN
        com.emu.apps: WARN


---
spring:
    profiles: development
    jpa:
        database-platform: org.hibernate.dialect.DerbyDialect
        generate-ddl: false
        show-sql: true
        hibernate:
            ddl-auto: create-drop
            properties:
               hibernate:
                  dialect: org.hibernate.dialect.DerbyDialect
        properties:
            hibernate:
              #use_sql_comments: true
              #show_sql: true
              #format_sql: true


server:
    address: 127.0.0.1

---
spring:
    profiles: production
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      generate-ddl: false
      show-sql: false
      hibernate:
          # dll-auto: none
          ddl-auto: create-drop
          properties:
              hibernate:
                  dialect: org.hibernate.dialect.PostgreSQLDialect
    datasource:
        driverClassName: org.postgresql.Driver
        url: jdbc:postgresql://192.168.1.100:5432/qcm
        username: mynotes
        password: mynotes
     

server:
    address: localhost
    port: 8080


