security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'

github:
  client:
    clientId: Iv1.acbf7009a5610786
    clientSecret: 90186ec1737e015cfe7ad3ca4fb58a69a5b272ba
    accessTokenUri: https://github.com/login/oauth/access_token
    userAuthorizationUri: https://github.com/login/oauth/authorize
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://api.github.com/user

local:
  client:
    clientId: moxjkLYOPMsJ0gHVZfJVjYiNNpymhXJS41qYDxfd
    clientSecret: J8FVJZfzJgDmy9LGuSgWXgrXwbkCCgZRjCBJNBVbEerG2Mgw5W2HdWXt40QJXdBsPT8vgIX4h5gmQlNrttoYSYvucbQ91rmDXlXouPQiyzgU1B3TC40z1RnUyXf6V4IE
    accessTokenUri: http://127.0.0.1:8000/o/token/
    userAuthorizationUri: http://127.0.0.1:8000/o/authorize
    clientAuthenticationScheme: form
    scope:
          - profile
  resource:
    userInfoUri: http://127.0.0.1:8000/api/v1/user/me/

logging:
  level:
    org.springframework.security: DEBUG