/**
 * Questionnaire REST API
 * Questionnaire REST API for webmarks.net
 *
 * OpenAPI spec version: 1.0
 * Contact: e.mul@free.fr
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import {Question} from './question.model';
import {Category} from './category.model';


export class Questionnaire {
  id?: number;
  title?: string;
  description?: string;
  category?: Category;
  questions?: Array<Question>;
  version?: number;
}
